spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 300800
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: zuev

jwt:
  secret: proselyte
  expiration: 604800
  header: Authorization

logging:
  file:
    name: logs.log
  level:
    com.edu_netcracker: TRACE

security:
  trusted-application-code: 95c9e20e-831c-11eb-8dcd-0242ac130003

bot:
  token: 1531954543:AAHgZt4bem3JygKOQ69JSD-oM51odOA2POg

mail:
  protocol: smtp
  smtp:
    auth: true
    starttls.enable: true
    debug: true
    starttls.required: true
  from: nikitazuev144@gmail.com
  host: smtp.gmail.com
  port: 587
  username: nikitazuev144@gmail.com
  password: nothing
---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/edu_notification_engine
    username: postgres
    password: ${POSTGRES_DATABASE_PASSWORD}
server:
  port: 8888
bot:
  token: 1553238646:AAE81yqhXVq_9XjYVEmkEay75U7Ej1ULd-U
mail:
  username: 8b4842764319d9
  password: 924aa1a2eb588e


