---
spring:
  profiles: zuev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 300800
server:
  port: 8080
bot:
  token: 1531954543:AAHgZt4bem3JygKOQ69JSD-oM51odOA2POg
mail:
  protocol: smtp
  smtp:
    auth: true
    starttls.enable: true
    debug: true
    starttls.required: true
  from: smtp.tests.zuevc@gmail.com
  host: smtp.gmail.com
  port: 587
  username: smtp.tests.zuev@gmail.com
  password: Glass71836

